name: release

on:
  workflow_run:
    workflows: [tests]
    branches: [main]
    types: [completed]

concurrency:
  group: build-${{ github.event.workflow_run.head_branch  }}
  cancel-in-progress: true

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
    - name: Install poetry
      run: pipx install poetry
    - name: Setup poetry
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - name: Build and publish
      run: poetry publish --build
